/**
 * Lista canonică a localităților din Republica Moldova (incl. Transnistria).
 * Folosită ca sursă unică pentru autocomplete în Properties/Index și WebOffers/Index.
 */
export const MOLDOVA_LOCALITIES = [
    'Anenii Noi',
    'Basarabeasca',
    'Bender mun.',
    'Briceni',
    'Bălți mun.',
    'Cahul',
    'Camenca',
    'Cantemir',
    'Chișinău',
    'Ciadîr-Lunga',
    'Cimișlia',
    'Comrat',
    'Criuleni',
    'Călărași',
    'Căușeni',
    'Dnestrovsk',
    'Dondușeni',
    'Drochia',
    'Dubăsari',
    'Edineț',
    'Florești',
    'Fălești',
    'Glodeni',
    'Grigoriopol',
    'Hîncești',
    'Ialoveni',
    'Leova',
    'Nisporeni',
    'Ocnița',
    'Orhei',
    'Rezina',
    'Rîbnița',
    'Rîșcani',
    'Slobozia',
    'Soroca',
    'Strășeni',
    'Sîngerei',
    'Taraclia',
    'Telenești',
    'Tiraspol mun.',
    'Ungheni',
    'Vulcănești',
    'Șoldănești',
    'Ștefan-Vodă',
];

// Sectoarele municipiului Chișinău + localitățile suburbane care fac parte
// administrativ din mun. Chișinău (comune, sate, micro-zone).
export const CHISINAU_DISTRICTS = [
    // Sectoare urbane
    'Aeroport',
    'Botanica',
    'Buiucani',
    'Centru',
    'Ciocana',
    'Poșta Veche',
    'Râșcani',
    'Sculeni',
    'Telecentru',
    // Localități suburbane
    'Bacioi',
    'Brăila',
    'Bubuieci',
    'Budești',
    'Buneți',
    'Bîc',
    'Ceroborta',
    'Cheltuitori',
    'Ciorescu',
    'Codru',
    'Colonița',
    'Condrița',
    'Cricova',
    'Cruzești',
    'Dobrogea',
    'Dumbrava',
    'Durlești',
    'Frumușica',
    'Făurești',
    'Ghidighici',
    'Goian',
    'Goianul Nou',
    'Grătiești',
    'Hulboaca',
    'Humulești',
    'Revaca',
    'Străisteni',
    'Stăuceni',
    'Sîngera',
    'Tohatin',
    'Trușeni',
    'Vadul lui Vodă',
    'Vatra',
    'Văduleni',
];
